import type { MenuItem } from "./store"

export const foodCategories = [
  { id: "all", name: "All" },
  { id: "burgers", name: "Burgers" },
  { id: "sides", name: "Sides" },
  { id: "drinks", name: "Drinks" },
  { id: "desserts", name: "Desserts" },
]

export const menuItems: MenuItem[] = [
  {
    id: "1",
    name: "Classic Cheeseburger",
    price: 12.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "burgers",
    description: "Juicy beef patty, cheddar cheese, lettuce, tomato, onion, pickles, special sauce on a brioche bun.",
  },
  {
    id: "2",
    name: "Spicy Chicken Sandwich",
    price: 11.5,
    image: "/placeholder.svg?height=400&width=400",
    category: "burgers",
    description: "Crispy fried chicken, spicy mayo, pickles, coleslaw on a toasted bun.",
  },
  {
    id: "3",
    name: "Veggie Burger",
    price: 10.99,
    image: "/placeholder.svg?height=400&width=400",
    category: "burgers",
    description: "Plant-based patty, avocado, lettuce, tomato, red onion, vegan aioli on a whole wheat bun.",
  },
  {
    id: "4",
    name: "French Fries",
    price: 4.0,
    image: "/placeholder.svg?height=400&width=400",
    category: "sides",
    description: "Crispy golden fries, lightly salted.",
  },
  {
    id: "5",
    name: "Onion Rings",
    price: 5.5,
    image: "/placeholder.svg?height=400&width=400",
    category: "sides",
    description: "Beer-battered onion rings, served with a tangy dipping sauce.",
  },
  {
    id: "6",
    name: "Coca-Cola",
    price: 2.5,
    image: "/placeholder.svg?height=400&width=400",
    category: "drinks",
    description: "Classic Coca-Cola, refreshing.",
  },
  {
    id: "7",
    name: "Milkshake",
    price: 6.0,
    image: "/placeholder.svg?height=400&width=400",
    category: "drinks",
    description: "Thick and creamy chocolate milkshake.",
  },
  {
    id: "8",
    name: "Chocolate Lava Cake",
    price: 7.0,
    image: "/placeholder.svg?height=400&width=400",
    category: "desserts",
    description: "Warm chocolate cake with a molten center, served with vanilla ice cream.",
  },
  {
    id: "9",
    name: "Apple Pie",
    price: 6.5,
    image: "/placeholder.svg?height=400&width=400",
    category: "desserts",
    description: "Classic apple pie with a flaky crust, served warm.",
  },
  {
    id: "10",
    name: "Grilled Chicken Salad",
    price: 13.5,
    image: "/placeholder.svg?height=400&width=400",
    category: "sides",
    description: "Fresh greens, grilled chicken, cherry tomatoes, cucumber, and a light vinaigrette.",
  },
  {
    id: "11",
    name: "Lemonade",
    price: 3.0,
    image: "/placeholder.svg?height=400&width=400",
    category: "drinks",
    description: "Freshly squeezed lemonade, perfectly tart and sweet.",
  },
  {
    id: "12",
    name: "Brownie Sundae",
    price: 8.0,
    image: "/placeholder.svg?height=400&width=400",
    category: "desserts",
    description: "Warm fudge brownie topped with vanilla ice cream, chocolate sauce, and whipped cream.",
  },
]
